version: "3"

services:
  app:
    build: .
    container_name: base-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: base-db
    tty: true
    environment:
      - POSTGRES_DB=eventex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - base-pgdata:/var/lib/postgresql/data

volumes:
  base-pgdata:
    external: true
